name: Continuous Integration

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Build project
        run: sbt +test

      - name: Compile examples
        run: sbt examples/compile
